name: Build package

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of an artifact"
        type: "string"
        required: false
        default: "package"

permissions:
  contents: read

jobs:
  build-pkg:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -U build twine
      - name: Build 📦 package
        run: python -m build
      - name: Check 📦 package
        run: twine check dist/*

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ inputs.artifact-name }}
          path: dist
