name: Publish to PyPI
on:
  push:
    tags: ["*"]  # this will run full workflow including publish to PyPI
  workflow_dispatch:

jobs:
  build:
    uses: "./.github/workflows/_build-pkg.yml"
    with:
      artifact-name: package

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: package
          path: dist
      - name: Install twine
        run: pip install -U "twine>=6.1.0" "packaging>=24.2"
      - name: Publish 📦 to PyPI
        # only run this for tags
        if: startsWith(github.event.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
