name: Top issues
on:
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:

jobs:
  ShowAndLabelTopIssues:
    name: Display and label top issues
    runs-on: ubuntu-latest
    if: github.repository == 'PyGithub/PyGithub'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Run top issues action
        uses: rickstaa/top-issues-action@7e8dda5d5ae3087670f9094b9724a9a091fc3ba1  # v1.3.101
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          label: true
          dashboard: true
          dashboard_show_total_reactions: true
          top_issues: true
          top_pull_requests: true
          top_list_size: 10
